logLevel: info

upstream:
  externalResolvers:
    - tcp-tls:dns.quad9.net
    - tcp-tls:1.1.1.1

conditional:
  mapping:
    xmple.io: udp:10.1.1.14

clientLookup:
  upstream: udp:10.1.1.14

blocking:
  blackLists:
    pihole:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://mirror1.malwaredomains.com/files/justdomains
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
    ads:
      #- https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
      #- https://adaway.org/hosts.txt
      #- https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
      - https://v.firebog.net/hosts/Easylist.txt
      - https://v.firebog.net/hosts/AdguardDNS.txt
      - https://v.firebog.net/hosts/Admiral.txt
    tracking:
      - https://v.firebog.net/hosts/Easyprivacy.txt
      - https://v.firebog.net/hosts/Prigent-Ads.txt
    amp:
      - https://www.github.developerdan.com/hosts/lists/amp-hosts-extended.txt
    malware:
      - https://www.malwaredomainlist.com/hostslist/hosts.txt
      - https://v.firebog.net/hosts/Prigent-Crypto.txt
      - https://v.firebog.net/hosts/Prigent-Malware.txt
      - https://v.firebog.net/hosts/Shalla-mal.txt

prometheus:
  enable: true
  path: /metrics

queryLog:
  dir: /logs
  logRetentionDays: 30

bootstrapDns: udp:1.1.1.1
port: 53
httpPort: 4000
